class CPlayerStats;
class MissionStats;
class cCharacterFX;
class CSpecialFX;
class cMoveMgr;
class IClientWeaponBase;
class MOD_ITEMs;
class CONVERT;
class WEAPON;
class AMMO;
class DSIGHTSTYLE;
struct IClientWeaponBase_vtbl
{
	void(__thiscall* IClientWeaponBaseq)(IClientWeaponBase* pthis);
	bool(__thiscall* OnMessage)(IClientWeaponBase* pthis, char, ILTMessage_Read*);
	bool(__thiscall* OnModelKey)(IClientWeaponBase* pthis, LTObject*, ArgList*);
	void(__thiscall* OnEnterWorld)(IClientWeaponBase* pthis);
	void(__thiscall* OnExitWorld)(IClientWeaponBase* pthis);
	bool(__thiscall* Init)(IClientWeaponBase* pthis, const WEAPON*);
	void(__thiscall* Term)(IClientWeaponBase* pthis);
	WeaponState(__thiscall* Update)(IClientWeaponBase* pthis, bool, FireType);
	void(__thiscall* ChangeAmmoWithReload)(IClientWeaponBase* pthis, unsigned __int16, bool);
	void(__thiscall* ChangeAmmoImmediate)(IClientWeaponBase* pthis, char, unsigned __int16, int, bool);
	void(__thiscall* ReloadClip)(IClientWeaponBase* pthis, int, bool, int, bool, bool, bool);
	void(__thiscall* ReloadClip1)(IClientWeaponBase* pthis, bool, int, bool, bool, bool);
	void(__thiscall* DecrementAmmo)(IClientWeaponBase* pthis);
	void(__thiscall* InitAmmoInClip)(IClientWeaponBase* pthis);
	void(__thiscall* SetCameraInfo)(IClientWeaponBase* pthis, const LTRotation*, const TVector3<float>*);
	void(__thiscall* ResetWeaponFilenames)(IClientWeaponBase* pthis);
	void(__thiscall* UpdateBob)(IClientWeaponBase* pthis, float, float);
	float(__thiscall* GetDynamicPerturb)(IClientWeaponBase* pthis);
	void(__thiscall* SetVisible)(IClientWeaponBase* pthis, bool);
	void(__thiscall* SetDisable)(IClientWeaponBase* pthis, int, bool);
	void(__thiscall* SetDisable1)(IClientWeaponBase* pthis, bool);
	void(__thiscall* Select)(IClientWeaponBase* pthis, int, bool, int);
	void(__thiscall* Select1)(IClientWeaponBase* pthis, bool);
	void(__thiscall* ClientSelect)(IClientWeaponBase* pthis);
	void(__thiscall* SetWeaponIndex)(IClientWeaponBase* pthis, int);
	int(__thiscall* GetWeaponIndex)(IClientWeaponBase* pthis);
	bool(__thiscall* Deselect)(IClientWeaponBase* pthis, void(__cdecl*)(int, void*), void*);
	bool(__thiscall* Activate)(IClientWeaponBase* pthis);
	void(__thiscall* Deactivate)(IClientWeaponBase* pthis);
	const WEAPON* (__thiscall* GetWeapon)(IClientWeaponBase* pthis);
	int(__thiscall* GetWeaponId)(IClientWeaponBase* pthis);
	const AMMO* (__thiscall* GetAmmo)(IClientWeaponBase* pthis);
	int(__thiscall* GetAmmoId)(IClientWeaponBase* pthis);
	int(__thiscall* GetAmmoInClip)(IClientWeaponBase* pthis);
	bool(__thiscall* HasAmmo)(IClientWeaponBase* pthis);
	bool(__thiscall* CanUseAmmo)(IClientWeaponBase* pthis, unsigned __int16);
	bool(__thiscall* CanChangeToAmmo)(IClientWeaponBase* pthis, unsigned __int16);
	unsigned __int16(__thiscall* GetNextAvailableAmmo)(IClientWeaponBase* pthis, unsigned __int16);
	bool(__thiscall* GetBestAvailableAmmoId)(IClientWeaponBase* pthis, int*);
	WeaponState(__thiscall* GetState)(IClientWeaponBase* pthis);
	CPWeaponStatusTyps(__thiscall* Get3rdPersonState)(IClientWeaponBase* pthis);
	bool(__thiscall* IsMeleeWeapon)(IClientWeaponBase* pthis);
	bool(__thiscall* IsFireButtonDown)(IClientWeaponBase* pthis);
	void(__thiscall* GetShellEjectPos)(IClientWeaponBase* pthis, TVector3<float>*);
	bool(__thiscall* WeaponNeedsCrosshair)(IClientWeaponBase* pthis);
	TVector3<float>* (__thiscall* GetMuzzleOffset)(IClientWeaponBase* pthis, TVector3<float>* result);
	void(__thiscall* SetMuzzleOffset)(IClientWeaponBase* pthis, const TVector3<float>*);
	TVector3<float>* (__thiscall* GetBreachOffset)(IClientWeaponBase* pthis, TVector3<float>* result);
	void(__thiscall* SetBreachOffset)(IClientWeaponBase* pthis, const TVector3<float>*);
	TVector3<float>* (__thiscall* GetWeaponOffset)(IClientWeaponBase* pthis, TVector3<float>* result);
	void(__thiscall* SetWeaponOffset)(IClientWeaponBase* pthis, const TVector3<float>*);
	LTObject* (__thiscall* GetHandle)(IClientWeaponBase* pthis);
	void(__thiscall* CreateMods)(IClientWeaponBase* pthis, ModKind);
	void(__thiscall* Load)(IClientWeaponBase* pthis, ILTMessage_Read*);
	void(__thiscall* Save)(IClientWeaponBase* pthis, ILTMessage_Write*);
	void(__thiscall* ResetWeapon)(IClientWeaponBase* pthis);
	void(__thiscall* SetPaused)(IClientWeaponBase* pthis, bool);
	void(__thiscall* ClearFiring)(IClientWeaponBase* pthis);
	bool(__thiscall* CanReload)(IClientWeaponBase* pthis);
	void(__thiscall* SetFPCWeaponFireState)(IClientWeaponBase* pthis, bool, bool);
	void(__thiscall* SetFPCWeaponReloadState)(IClientWeaponBase* pthis, int);
	void(__thiscall* SetFPCWeaponDynamicPerturb)(IClientWeaponBase* pthis, float);
	void(__thiscall* SetFPCDashState)(IClientWeaponBase* pthis, bool);
	bool(__thiscall* ToggleTripleShotMode)(IClientWeaponBase* pthis);
	bool(__thiscall* IsTripleShotMode)(IClientWeaponBase* pthis);
	bool(__thiscall* ToggleContinuousFireMode)(IClientWeaponBase* pthis);
	bool(__thiscall* IsContinuousFireMode)(IClientWeaponBase* pthis);
	bool(__thiscall* AttachPlayersMod)(IClientWeaponBase* pthis, int, bool, bool);
	bool(__thiscall* DetachPlayersMod)(IClientWeaponBase* pthis, ModKind, bool);
	void(__thiscall* DetachPlayersAllMods)(IClientWeaponBase* pthis);
	bool(__thiscall* IsAttached)(IClientWeaponBase* pthis, int);
	TVector3<float>* (__thiscall* GetModOffset)(IClientWeaponBase* pthis, TVector3<float>* result, ModKind, bool);
	void(__thiscall* SetModOffset)(IClientWeaponBase* pthis, ModKind, TVector3<float>, bool);
	const MOD_ITEMs* (__thiscall* GetCurrentMod)(IClientWeaponBase* pthis, ModKind);
	const DSIGHTSTYLE* (__thiscall* GetDSightStyle)(IClientWeaponBase* pthis);
	bool(__thiscall* SetDSightStyle)(IClientWeaponBase* pthis, int);
	int(__thiscall* GetWeaponShotsPerClip)(IClientWeaponBase* pthis);
	int(__thiscall* GetAmmoMaxAmount)(IClientWeaponBase* pthis);
	void(__thiscall* SetAmmoInClip)(IClientWeaponBase* pthis, int);
	bool(__thiscall* GetFiring)(IClientWeaponBase* pthis);
	float(__thiscall* GetLastFired)(IClientWeaponBase* pthis);
	void(__thiscall* SetLastFired)(IClientWeaponBase* pthis, float);
	float(__thiscall* GetLastAltFired)(IClientWeaponBase* pthis);
	void(__thiscall* SetLastAltFired)(IClientWeaponBase* pthis, float);
	void(__thiscall* SetInitClientWeapon)(IClientWeaponBase* pthis, int);
	int(__thiscall* GetInitClientWeapon)(IClientWeaponBase* pthis);
	void(__thiscall* SetConvert)(IClientWeaponBase* pthis, int, int);
	const CONVERT* (__thiscall* GetConvertData)(IClientWeaponBase* pthis);
	const int* (__thiscall* GetConvert)(IClientWeaponBase* pthis);
	float(__thiscall* GetMaxRandomWag)(IClientWeaponBase* pthis);
	float(__thiscall* GetMaxCamRecoilWag)(IClientWeaponBase* pthis);
	float(__thiscall* GetBaseCamRecoilWagR)(IClientWeaponBase* pthis);
	float(__thiscall* GetBaseCamRecoilWagL)(IClientWeaponBase* pthis);
	float(__thiscall* GetMaxRandomPitch)(IClientWeaponBase* pthis);
	float(__thiscall* GetMaxCamRecoilPitch)(IClientWeaponBase* pthis);
	float(__thiscall* GetBaseCamRecoilPitch)(IClientWeaponBase* pthis);
	float(__thiscall* GetBaseCamRecoilAccelPitch)(IClientWeaponBase* pthis);
	float(__thiscall* GetTripleShotMaxCamRecoilPitch)(IClientWeaponBase* pthis);
	float(__thiscall* GetTripleShotBaseCamRecoilPitch)(IClientWeaponBase* pthis);
	int(__thiscall* GetMinPerturb)(IClientWeaponBase* pthis);
	int(__thiscall* GetMaxPerturb)(IClientWeaponBase* pthis);
	float(__thiscall* GetDuckPerturb)(IClientWeaponBase* pthis);
	float(__thiscall* GetDuckMovePerturb)(IClientWeaponBase* pthis);
	int(__thiscall* GetZoomedMinPerturb)(IClientWeaponBase* pthis);
	int(__thiscall* GetZoomedMaxPerturb)(IClientWeaponBase* pthis);
	int(__thiscall* GetTripleShotMinPerturb)(IClientWeaponBase* pthis);
	int(__thiscall* GetTripleShotMaxPerturb)(IClientWeaponBase* pthis);
	bool(__thiscall* GetShellEjectLeftDual)(IClientWeaponBase* pthis);
};

struct CMoveMgr_vtbl
{
	void(__thiscall* cMoveMgr1)(cMoveMgr* pthis);
	float(__thiscall* CalculateMovementPenalty)(cMoveMgr* pthis);
	bool(__thiscall* IsHoldingFlag)(cMoveMgr* pthis);
};
struct CSpecialFX_vtblqq
{
	void(__thiscall* CSpecialFXq)(CSpecialFX* pthis);
	void(__thiscall* Term)(CSpecialFX* pthis);
	unsigned int(__thiscall* CreateObject)(CSpecialFX* pthis, ILTClientDLL*);
	unsigned int(__thiscall* Init)(CSpecialFX* pthis, SFXCREATESTRUCT*);
	unsigned int(__thiscall* Init1)(CSpecialFX* pthis, int*, ILTMessage_Read*);
	unsigned int(__thiscall* Update)(CSpecialFX* pthis);
	void(__thiscall* Render)(CSpecialFX* pthis, int*);
	void(__thiscall* WantRemove)(CSpecialFX* pthis, unsigned int);
	void(__thiscall* OnObjectFileNames)(CSpecialFX* pthis);
	void(__thiscall* HandleTouch)(CSpecialFX* pthis, const CollisionInfo*);
	void(__thiscall* OnModelKey)(CSpecialFX* pthis, int*, ArgList*);
	unsigned int(__thiscall* OnServerMessage)(CSpecialFX* pthis, ILTMessage_Read*);
	unsigned int(__thiscall* GetSFXID)(CSpecialFX* pthis);
	char(__thiscall* GetMenuLayer)(CSpecialFX* pthis);
};
struct CPlayerStats_vtbl
{
	unsigned int(__thiscall* Init)(CPlayerStats* pthis);
	void(__thiscall* Term)(CPlayerStats* pthis);
	void(__thiscall* OnEnterWorld)(CPlayerStats* pthis, unsigned int);
	void(__thiscall* OnExitWorld)(CPlayerStats* pthis);
	void(__thiscall* Update)(CPlayerStats* pthis);
	void(__thiscall* UpdatePlayerWeapon)(CPlayerStats* pthis, char, unsigned __int16, unsigned __int16, unsigned int);
	void(__thiscall* ResetStats)(CPlayerStats* pthis);
	void(__thiscall* Clear)(CPlayerStats* pthis);
	void(__thiscall* UpdateHealth)(CPlayerStats* pthis, unsigned int);
	void(__thiscall* UpdateArmor)(CPlayerStats* pthis, unsigned int);
	void(__thiscall* UpdateMaxHealth)(CPlayerStats* pthis, unsigned int);
	void(__thiscall* UpdateMaxArmor)(CPlayerStats* pthis, unsigned int);
	void(__thiscall* UpdateProgress)(CPlayerStats* pthis, unsigned int);
	void(__thiscall* UpdateMaxProgress)(CPlayerStats* pthis, unsigned int);
	void(__thiscall* UpdateAmmo)(CPlayerStats* pthis, int, unsigned __int16, unsigned __int16, unsigned int, unsigned int, unsigned int, int);
	void(__thiscall* UpdateGear)(CPlayerStats* pthis, char, unsigned __int16, char, char);
	void(__thiscall* UpdateMod)(CPlayerStats* pthis, unsigned __int16);
	void(__thiscall* DropWeapon)(CPlayerStats* pthis, int, unsigned __int16);
	void(__thiscall* ResetAllWeapons)(CPlayerStats* pthis);
	void(__thiscall* ResetMissionStats)(CPlayerStats* pthis);
	void(__thiscall* ClearMissionInfo)(CPlayerStats* pthis);
	int(__thiscall* GetMissionDamage)(CPlayerStats* pthis);
	MissionStats* (__thiscall* GetMissionStats)(CPlayerStats* pthis);
	void(__thiscall* Save)(CPlayerStats* pthis, ILTMessage_Write*);
	void(__thiscall* Load)(CPlayerStats* pthis, ILTMessage_Read*);
	unsigned __int16(__thiscall* GetMod)(CPlayerStats* pthis, ModType, const WEAPON*);
	unsigned __int16(__thiscall* GetSilencer)(CPlayerStats* pthis, const WEAPON*);
	unsigned __int16(__thiscall* GetScope)(CPlayerStats* pthis, const WEAPON*);
	unsigned int(__thiscall* CanBeSilenced)(CPlayerStats* pthis);
	unsigned int(__thiscall* CanHaveScope)(CPlayerStats* pthis);
	unsigned __int16(__thiscall* GetDotSight)(CPlayerStats* pthis, const WEAPON*);
	unsigned int(__thiscall* CanHaveDotSight)(CPlayerStats* pthis);
	unsigned int(__thiscall* GetAmmoCount)(CPlayerStats* pthis, unsigned __int16);
	unsigned int(__thiscall* HaveWeapon)(CPlayerStats* pthis, int, unsigned __int16);
	unsigned int(__thiscall* HaveWeapon1)(CPlayerStats* pthis, unsigned __int16);
	unsigned int(__thiscall* HaveMod)(CPlayerStats* pthis, unsigned __int16);
	unsigned int(__thiscall* HaveGear)(CPlayerStats* pthis, char);
	unsigned int(__thiscall* CanUseWeapon)(CPlayerStats* pthis, unsigned __int16);
	unsigned int(__thiscall* CanUseAmmo)(CPlayerStats* pthis, unsigned __int16);
	unsigned int(__thiscall* CanUseMod)(CPlayerStats* pthis, unsigned __int16);
	unsigned int(__thiscall* CanUseGear)(CPlayerStats* pthis, char);
	void(__thiscall* Setup)(CPlayerStats* pthis);
	unsigned int(__thiscall* GetHealth)(CPlayerStats* pthis);
	unsigned int(__thiscall* GetMaxHealth)(CPlayerStats* pthis);
	unsigned int(__thiscall* GetArmor)(CPlayerStats* pthis);
	unsigned int(__thiscall* GetMaxArmor)(CPlayerStats* pthis);
	unsigned int(__thiscall* GetProgress)(CPlayerStats* pthis);
	unsigned int(__thiscall* GetMaxProgress)(CPlayerStats* pthis);
	unsigned __int16(__thiscall* GetCurrentWeapon)(CPlayerStats* pthis);
	unsigned __int16(__thiscall* GetCurrentAmmo)(CPlayerStats* pthis);
	unsigned int(__thiscall* GetCurrentAmmoCount)(CPlayerStats* pthis);
	void(__thiscall* SetPlayerDash)(CPlayerStats* pthis, bool, int);
	int(__thiscall* GetDashStartTime)(CPlayerStats* pthis);
	void(__thiscall* SetDashResetTime)(CPlayerStats* pthis, int);
	void(__thiscall* SetPlayerDashEnd)(CPlayerStats* pthis, bool);
	int(__thiscall* GetPlayerDash)(CPlayerStats* pthis);
	int(__thiscall* GetDashGauge)(CPlayerStats* pthis);
	int(__thiscall* GetDashGaugeRec)(CPlayerStats* pthis);
	float(__thiscall* GetDashCurrentStamina)(CPlayerStats* pthis);
	eDashGageState(__thiscall* GetSPGageState)(CPlayerStats* pthis);
	void(__thiscall* SetSPGageState)(CPlayerStats* pthis, eDashGageState);
	void(__thiscall* SetDashGauge)(CPlayerStats* pthis, int);
	void(__thiscall* SetDashGaugeRec)(CPlayerStats* pthis, int);
	void(__thiscall* SetDashCurrentStamina)(CPlayerStats* pthis, float);
	void(__thiscall* ResetDashStamina)(CPlayerStats* pthis);
	void(__thiscall* SetAmmoInClip)(CPlayerStats* pthis, int);
	int(__thiscall* GetAmmoInClip)(CPlayerStats* pthis);
	void(__thiscall* SetPickupItem)(CPlayerStats* pthis, bool);
	bool(__thiscall* GetPickupItem)(CPlayerStats* pthis);
	int(__thiscall* SetJumped)(CPlayerStats* pthis, int);
	int(__thiscall* GetJumped)(CPlayerStats* pthis);
};
struct CCharacterFX_vtbl
{
	void(__thiscall* CSpecialFXs)(CSpecialFX* pthis);
	void(__thiscall* Term)(CSpecialFX* pthis);
	unsigned int(__thiscall* CreateObject)(CSpecialFX* pthis, ILTClientDLL*);
	unsigned int(__thiscall* Init)(CSpecialFX* pthis, SFXCREATESTRUCT*);
	unsigned int(__thiscall* Init1)(CSpecialFX* pthis, LTObject*, ILTMessage_Read*);
	unsigned int(__thiscall* Update)(CSpecialFX* pthis);
	void(__thiscall* Render)(CSpecialFX* pthis, LTObject*);
	void(__thiscall* WantRemove)(CSpecialFX* pthis, unsigned int);
	void(__thiscall* OnObjectFileNames)(CSpecialFX* pthis);
	void(__thiscall* HandleTouch)(CSpecialFX* pthis, const CollisionInfo*);
	void(__thiscall* OnModelKey)(CSpecialFX* pthis, LTObject*, ArgList*);
	unsigned int(__thiscall* OnServerMessage)(CSpecialFX* pthis, ILTMessage_Read*);
	unsigned int(__thiscall* GetSFXID)(CSpecialFX* pthis);
	char(__thiscall* GetMenuLayer)(CSpecialFX* pthis);
	void(__thiscall* ChangeModel)(cCharacterFX* pthis, class ModelButeReader*, int);
	float(__thiscall* GetTwistYaw)(cCharacterFX* pthis);
	float(__thiscall* GetCharPitch)(cCharacterFX* pthis);
	unsigned int(__thiscall* GetPlayerControlFlags)(cCharacterFX* pthis);
	LTRotation* (__thiscall* GetPlayerCameraRot)(cCharacterFX* pthis, LTRotation* result);
	void(__thiscall* SetPlayerCameraRot)(cCharacterFX* pthis, LTRotation);
	int(__thiscall* GetPlayerCurrentWeaponID)(cCharacterFX* pthis);
	bool(__thiscall* GetPlayerZoomedIn)(cCharacterFX* pthis);
	void(__thiscall* SetPlayerCurrentWeaponID)(cCharacterFX* pthis, int, LTObject*);
	TVector3<float>* (__thiscall* GetPlayerCameraPos)(cCharacterFX* pthis, TVector3<float>* result);
	void(__thiscall* SetPlayerCameraPos)(cCharacterFX* pthis, TVector3<float>);
	int(__thiscall* GetPlayerModID)(cCharacterFX* pthis, ModKind);
	bool(__thiscall* GetPlayerDotSighted)(cCharacterFX* pthis);
	unsigned __int16(__thiscall* GetHealth)(cCharacterFX* pthis);
	unsigned __int16(__thiscall* GetArmor)(cCharacterFX* pthis);
	int(__thiscall* GetTeam)(cCharacterFX* pthis);
	void(__thiscall* SetTeam)(cCharacterFX* pthis, int);
	int(__thiscall* GetId)(cCharacterFX* pthis);
	void(__thiscall* SetId)(cCharacterFX* pthis, unsigned int);
	bool(__thiscall* IsBombPlantProgress)(cCharacterFX* pthis);
	bool(__thiscall* IsBombDefuseProgress)(cCharacterFX* pthis);
	void(__thiscall* ResetAimAtTracking)(cCharacterFX* pthis);
};
