
struct ILTCSBaseq
{
	IBase* baseclass_0;
	unsigned int(__cdecl* GetTcpIpAddress)(char*, unsigned int, unsigned __int16*);
};

class ILTClientDLL
{
public:
	ILTCSBaseq baseclass_0;
	FileEntry* (__cdecl* GetFileList)(const char*);
	void(__cdecl* FreeFileList)(FileEntry*);
	unsigned int(__cdecl* WriteConfigFileFields)(const char*, unsigned int, const char**);
	unsigned int(__cdecl* WriteConfigFile)(const char*);
	unsigned int(__cdecl* ReadConfigFile)(const char*);
	void(__cdecl* GetAxisOffsets)(float*);
	void(__cdecl* PlayJoystickEffect)(const char*, float, float);
	unsigned int(__cdecl* GetSoundTimer)(HLTSOUND_t*, float*);
	unsigned int(__cdecl* GetSoundData)(HLTSOUND_t*, __int16**, char**, unsigned int*, unsigned int*);
	unsigned int(__cdecl* GetSoundOffset)(HLTSOUND_t*, unsigned int*, unsigned int*);
	bool(__cdecl* IsDone)(HLTSOUND_t*);
	void(__cdecl* GetListener)(bool*, TVector3<float>*, LTRotation*);
	bool(__cdecl* IntersectSegment)(IntersectQueryCA&, IntersectInfoCA&);
	//bool(__cdecl* IntersectAndPenetrateSegment)(IntersectQueryCA& Query, IntersectInfoCA* pInfo);  //??
	bool(__cdecl* IntersectSweptSphere)(const TVector3<float>*, const TVector3<float>*, float, TVector3<float>*, TVector3<float>*);
	bool(__cdecl* CastRay)(IntersectQuery*, IntersectInfo*);
	void(__cdecl* SetObjectPosAndRotation)(LTObject*, const TVector3<float>*, const LTRotation*);
	unsigned int(__cdecl* FindObjectsInSphere)(const TVector3<float>*, float, LTObject**, unsigned int, unsigned int*, unsigned int*);
	unsigned int(__cdecl* FindObjectsInBox)(const TVector3<float>*, float, LTObject**, unsigned int, unsigned int*, unsigned int*);
	unsigned int(__cdecl* GetGameMode)(int*);
	unsigned int(__cdecl* StartGame)(StartGameRequest*);
	unsigned int(__cdecl* HostServerAppMessage)(char*);
	unsigned int(__cdecl* GetLocalClientID)(unsigned int*);
	void(__cdecl* Disconnect)();
	bool(__cdecl* IsConnected)();
	void(__cdecl* Shutdown)();
	void (*ShutdownWithMessage)(const char*, ...);
	unsigned int(__cdecl* FlipScreen)(unsigned int);
	unsigned int(__cdecl* Start3D)();
	unsigned int(__cdecl* RenderCamera)(int*, float);
	unsigned int(__cdecl* ClearScreen)(LTRectq*, unsigned int, LTRGB*);
	unsigned int(__cdecl* RenderObjects)(LTObject*, LTObject**, int, float);
	unsigned int(__cdecl* MakeCubicEnvMap)(LTObject*, unsigned int, const char*);
	unsigned int(__cdecl* StartOptimized2D)();
	unsigned int(__cdecl* EndOptimized2D)();
	unsigned int(__cdecl* SetOptimized2DBlend)(LTSurfaceBlend);
	unsigned int(__cdecl* GetOptimized2DBlend)(LTSurfaceBlend*);
	unsigned int(__cdecl* End3D)(unsigned int);
	unsigned int(__cdecl* GetOptimized2DColor)(unsigned int*);
	unsigned int(__cdecl* SetOptimized2DColor)(unsigned int);
	RMode* (__cdecl* GetRenderModes)();
	void(__cdecl* RelinquishRenderModes)(RMode*);
	unsigned int(__cdecl* GetRenderMode)(RMode*);
	unsigned int(__cdecl* SetRenderMode)(RMode*);
	unsigned int(__cdecl* SetScreenRenderMode)(RMode*);
	unsigned int(__cdecl* SetDialogBoxMode)(bool);
	int(__cdecl* GetSupportedMSTypes)(const RMode*, int*, int);
	unsigned int(__cdecl* ShutdownRender)(unsigned int);
	HLTFONT_tq* (__cdecl* CreateFontq)(const char*, int, int, bool, bool, bool);
	void(__cdecl* DeleteFont)(HLTFONT_tq*);
	unsigned int(__cdecl* SetFontExtraSpace)(HLTFONT_tq*, int);
	unsigned int(__cdecl* GetFontExtraSpace)(HLTFONT_tq*, int*);
	unsigned int(__cdecl* RegisterConsoleProgram)(const char*, void(__cdecl*)(int, char**));
	unsigned int(__cdecl* UnregisterConsoleProgram)(const char*);
	HCONSOLEVAR_tq* (__cdecl* GetConsoleVar)(const char*);
	unsigned int(__cdecl* CreateColor)(float, float, float, bool);
	void(__cdecl* DeleteColor)(unsigned int);
	unsigned int(__cdecl* SetupColor1)(float, float, float, bool);
	unsigned int(__cdecl* SetupColor2)(float, float, float, bool);
	unsigned int(__cdecl* GetBorderSize)(HSURFACE_tq*, unsigned int, LTRectq*);
	unsigned int(__cdecl* OptimizeSurface)(HSURFACE_tq*, unsigned int);
	unsigned int(__cdecl* UnoptimizeSurface)(HSURFACE_tq*);
	HSURFACE_tq* (__cdecl* GetScreenSurface)();
	unsigned int(__cdecl* CreateHeightmapFromBitmap)(const char*, unsigned int*, unsigned int*, char**);
	HSURFACE_tq* (__cdecl* CreateSurfaceFromBitmap)(char*);
	unsigned int(__cdecl* FreeHeightmap)(char*);
	HSURFACE_tq* (__cdecl* CreateSurfaceFromString)(HLTFONT_tq*, struct HSTRING_t*, unsigned int, unsigned int, int, int);
	HSURFACE_tq* (__cdecl* CreateSurface)(unsigned int, unsigned int);
	unsigned int(__cdecl* DeleteSurface)(HSURFACE_tq*);
	void* (__cdecl* GetSurfaceUserData)(HSURFACE_tq*);
	void(__cdecl* SetSurfaceUserData)(HSURFACE_tq*, void*);
	unsigned int(__cdecl* GetPixel)(HSURFACE_tq*, unsigned int, unsigned int, unsigned int*);
	unsigned int(__cdecl* SetPixel)(HSURFACE_tq*, unsigned int, unsigned int, unsigned int);
	void(__cdecl* GetStringDimensions)(HLTFONT_tq*, HSTRING_t*, int*, int*);
	void(__cdecl* DrawStringToSurface)(HSURFACE_tq*, HLTFONT_tq*, HSTRING_t*, LTRectq*, unsigned int, unsigned int);
	void(__cdecl* GetSurfaceDims)(HSURFACE_tq*, unsigned int*, unsigned int*);
	bool(__cdecl* DrawBitmapToSurface)(HSURFACE_tq*, const char*, const LTRectq*, int, int);
	unsigned int(__cdecl* DrawSurfaceMasked)(HSURFACE_tq*, HSURFACE_tq*, HSURFACE_tq*, LTRectq*, int, int, unsigned int);
	unsigned int(__cdecl* DrawSurfaceSolidColor)(HSURFACE_tq*, HSURFACE_tq*, LTRectq*, int, int, unsigned int, unsigned int);
	unsigned int(__cdecl* DrawSurfaceToSurface)(HSURFACE_tq*, HSURFACE_tq*, LTRectq*, int, int);
	unsigned int(__cdecl* DrawSurfaceToSurfaceTransparent)(HSURFACE_tq*, HSURFACE_tq*, LTRectq*, int, int, unsigned int);
	unsigned int(__cdecl* ScaleSurfaceToSurface)(HSURFACE_tq*, HSURFACE_tq*, LTRectq*, LTRectq*);
	unsigned int(__cdecl* ScaleSurfaceToSurfaceTransparent)(HSURFACE_tq*, HSURFACE_tq*, LTRectq*, LTRectq*, unsigned int);
	unsigned int(__cdecl* ScaleSurfaceToSurfaceSolidColor)(HSURFACE_tq*, HSURFACE_tq*, LTRectq*, LTRectq*, unsigned int, unsigned int);
	unsigned int(__cdecl* WarpSurfaceToSurface)(HSURFACE_tq*, HSURFACE_tq*, LTWarpPtq*, int);
	unsigned int(__cdecl* WarpSurfaceToSurfaceTransparent)(HSURFACE_tq*, HSURFACE_tq*, LTWarpPtq*, int, unsigned int);
	unsigned int(__cdecl* WarpSurfaceToSurfaceSolidColor)(HSURFACE_tq*, HSURFACE_tq*, LTWarpPtq*, int, unsigned int, unsigned int);
	unsigned int(__cdecl* TransformSurfaceToSurface)(HSURFACE_tq*, HSURFACE_tq*, LTFloatPtq*, int, int, float, float, float);
	unsigned int(__cdecl* TransformSurfaceToSurfaceTransparent)(HSURFACE_tq*, HSURFACE_tq*, LTFloatPtq*, int, int, float, float, float, unsigned int);
	unsigned int(__cdecl* FillRect)(HSURFACE_tq*, LTRectq*, unsigned int);
	unsigned int(__cdecl* GetSurfaceAlpha)(HSURFACE_tq*, float*);
	unsigned int(__cdecl* SetSurfaceAlpha)(HSURFACE_tq*, float);
	void(__cdecl* StartCounter)(LTCounterq*);
	unsigned int(__cdecl* EndCounter)(LTCounterq*);
	void(__cdecl* SetInputState)(bool);
	void(__cdecl* SetMouseMovement)(bool);
	unsigned int(__cdecl* ClearInput)();
	DeviceBinding* (__cdecl* GetDeviceBindings)(unsigned int);
	void(__cdecl* FreeDeviceBindings)(DeviceBinding*);
	bool(__cdecl* ClearBinding)(const char*, const char*);
	bool(__cdecl* AddBinding)(const char*, const char*, const char*, float, float);
	unsigned int(__cdecl* StartDeviceTrack)(unsigned int, unsigned int);
	unsigned int(__cdecl* TrackDevice)(DeviceInputq*, unsigned int*);
	unsigned int(__cdecl* EndDeviceTrack)();
	DeviceObject* (__cdecl* GetDeviceObjects)(unsigned int);
	void(__cdecl* FreeDeviceObjects)(DeviceObject*);
	unsigned int(__cdecl* GetDeviceName)(unsigned int, char*, unsigned int);
	unsigned int(__cdecl* IsDeviceEnabled)(const char*, bool*);
	unsigned int(__cdecl* EnableDevice)(const char*);
	unsigned int(__cdecl* GetNumRawDevices)();
	unsigned int(__cdecl* GetRawDeviceData)(unsigned int, void*);
	unsigned int(__cdecl* GetRawDeviceDataSize)(unsigned int);
	unsigned int(__cdecl* GetRawDeviceActuatorDataSize)(unsigned int);
	unsigned int(__cdecl* SetRawDeviceActuatorData)(unsigned int, void*);
	float(__cdecl* GetGameTime)();
	unsigned int(__cdecl* GetGameTimeMS)();
	float(__cdecl* GetGameFrameTime)();
	unsigned int(__cdecl* GetGameFrameTimeMS)();
	long double(__cdecl* GetVisibleGameTime)();
	unsigned int(__cdecl* GetVisibleGameTimeMS)();
	long double(__cdecl* GetClientGameTime)();
	unsigned int(__cdecl* GetClientGameTimeMS)();
	unsigned int(__cdecl* GetClientPlayerMovementGameTimeMS)();
	void (*DebugOut)(const char*, ...);
	unsigned int(__cdecl* GetSkyDef)(SkyDef*);
	bool(__cdecl* IsCommandOn)(int);
	void(__cdecl* RunConsoleString)(const char*);
	LTObject* (__cdecl* GetClientObject)();
	void(__cdecl* GetGlobalLightScale)(TVector3<float>*);
	void(__cdecl* SetGlobalLightScale)(const TVector3<float>*);
	void(__cdecl* OffsetGlobalLightScale)(const TVector3<float>*);
	LTObject* (__cdecl* CreateObject)(ObjectCreateStruct*);
	unsigned int(__cdecl* GetObjectScale)(LTObject*, TVector3<float>*);
	unsigned int(__cdecl* SetObjectScale)(LTObject*, const TVector3<float>*);
	void(__cdecl* SetObjectRotation)(LTObject*, const LTRotation*);
	void(__cdecl* GetObjectColor)(LTObject*, float*, float*, float*, float*);
	void(__cdecl* SetObjectColor)(LTObject*, float, float, float, float);
	void* (__cdecl* GetObjectUserData)(LTObject*);
	void(__cdecl* SetObjectUserData)(LTObject*, void*);
	unsigned int(__cdecl* Get3DCameraPt)(LTObject*, int, int, TVector3<float>*);
	void(__cdecl* GetCameraFOV)(LTObject*, float*, float*);
	void(__cdecl* SetCameraFOV)(int*, float, float);
	void(__cdecl* GetCameraRect)(LTObject*, bool*, int*, int*, int*, int*);
	void(__cdecl* SetCameraRect)(LTObject*, bool, int, int, int, int);
	bool(__cdecl* GetCameraLightAdd)(LTObject*, TVector3<float>*);
	bool(__cdecl* SetCameraLightAdd)(LTObject*, const TVector3<float>*);
	unsigned int(__cdecl* SetupParticleSystem)(LTObject*, const char*, float, unsigned int, float);
	void(__cdecl* AddParticles)(LTObject*, unsigned int, const TVector3<float>*, const TVector3<float>*, const TVector3<float>*, const TVector3<float>*, const TVector3<float>*, const TVector3<float>*, float, float);
	bool(__cdecl* GetParticles)(LTObject*, LTParticle**, LTParticle**);
	void(__cdecl* RemoveParticle)(LTObject*, LTParticle*);
	unsigned int(__cdecl* OptimizeParticles)(LTObject*);
	unsigned int(__cdecl* SortParticles)(LTObject*, const TVector3<float>*, unsigned int);
	unsigned int(__cdecl* SetParticleSystemEffectShaderID)(LTObject*, unsigned int);
	HLTLINE_tq* (__cdecl* GetNextLine)(LTObject*, HLTLINE_tq*);
	void(__cdecl* GetLineInfo)(HLTLINE_tq*, LTLineq*);
	void(__cdecl* SetLineInfo)(HLTLINE_tq*, LTLineq*);
	HLTLINE_tq* (__cdecl* AddLine)(LTObject*, LTLineq*);
	void(__cdecl* RemoveLine)(LTObject*, HLTLINE_tq*);
	bool(__cdecl* SetupVolumeEffect)(LTObject*, VolumeEffectInfo*);
	unsigned int(__cdecl* SetVolumeEffectEffectShaderID)(LTObject*, unsigned int);
	unsigned int* (__cdecl* GetParticleBlockersInAABB)(const TVector3<float>*, const TVector3<float>*, unsigned int*);
	bool(__cdecl* GetParticleBlockerEdgesXZ)(unsigned int, LTPlane*, unsigned int*, LTPlane**);
	void(__cdecl* GetParticleTermSnowFx)(unsigned int*);
	bool(__cdecl* SetupPolyGrid)(LTObject*, unsigned int, unsigned int, unsigned int, bool*);
	unsigned int(__cdecl* SetPolyGridTexture)(LTObject*, const char*);
	unsigned int(__cdecl* SetPolyGridEnvMap)(LTObject*, const char*);
	unsigned int(__cdecl* GetPolyGridTextureInfo)(LTObject*, float*, float*, float*, float*, float*, float*);
	unsigned int(__cdecl* SetPolyGridTextureInfo)(LTObject*, float, float, float, float, float, float);
	unsigned int(__cdecl* GetPolyGridInfo)(LTObject*, char**, unsigned int*, unsigned int*, PGColor**);
	unsigned int(__cdecl* SetPolyGridEffectShaderID)(LTObject*, unsigned int);
	unsigned int(__cdecl* InitNetworking)(const char*, unsigned int);
	unsigned int(__cdecl* GetServiceList)(NetService**);
	unsigned int(__cdecl* FreeServiceList)(NetService*);
	unsigned int(__cdecl* SelectService)(HNETSERVICE_t*);
	unsigned int(__cdecl* GetSessionList)(NetSession**, const char*);
	unsigned int(__cdecl* FreeSessionList)(NetSession*);
	unsigned int(__cdecl* AddInternetDriver)();
	unsigned int(__cdecl* RemoveInternetDriver)();
	unsigned int(__cdecl* GetVersionInfoExt)(LTVersionInfoExt_tq*);
	unsigned int(__cdecl* GetPerformanceInfo)(LTPerformanceInfo_tq*);
	unsigned int(__cdecl* SetConsoleEnable)(bool);
	void(__cdecl* GetLightColor)(int*, float*, float*, float*);
	void(__cdecl* SetLightColor)(int*, float, float, float);
	float(__cdecl* GetLightRadius)(LTObject*);
	void(__cdecl* SetLightRadius)(LTObject*, float);
	unsigned int(__cdecl* ClipSprite)(LTObject*, HPOLY);
	unsigned int(__cdecl* GetPolyTextureFlags)(HPOLY, unsigned int*);
	unsigned int(__cdecl* SetModelHook)(void(__cdecl*)(ModelHookData*, void*), void*);
	unsigned int(__cdecl* GetEngineHook)(char*, void**);
	unsigned int(__cdecl* QueryGraphicDevice)(LTGraphicsCaps*);
	unsigned int(__cdecl* SetWebWindow)(bool, char*);
	int(__cdecl* GetNodeNum)(LTObject*);
	int(__cdecl* GetSocketNum)(LTObject*);
	int(__cdecl* GetAnimNum)(LTObject*);
	const char* (__cdecl* GetNodeIdToName)(LTObject*, int);
	const char* (__cdecl* GetSocketIdToName)(LTObject*, int);
	const char* (__cdecl* GetAnimIdToName)(LTObject*, int);
	void(__cdecl* UpdateGamma)();
	void* (__cdecl* GetInstance)();
	void(__cdecl* SetRollOffFactor)(float);
	void(__cdecl* InitRunTimeResources)(const std::vector<stPreLoadListItem, std::allocator<stPreLoadListItem> >*, bool);
	void(__cdecl* PlayBackgroundStream)(const char*, bool, float);
	void(__cdecl* StopBackgroundStream)();
	void(__cdecl* PauseBackgroundStream)();
	void(__cdecl* ResumeBackgroundStream)();
	int(__cdecl* GetVolumeBackgroundStream)();
	void(__cdecl* SetVolumeBackgroundStream)(int);
	int(__cdecl* GetLoopBackgroundStream)();
	void(__cdecl* SetLoopBackgroundStream)(bool);
	bool(__cdecl* IsInFadeOut)();
	bool(__cdecl* IsPlayable)(const char*);
	bool(__cdecl* IsPlaying)();
	const char* (__cdecl* GetPassport)();
	void(__cdecl* SetPassport)(const wchar_t*);
	void(__cdecl* SetUid)(int);
	void(__cdecl* SetCharacterName)(const wchar_t*);
	void(__cdecl* MakeScreenShot)(const char*);
	ID3DXBuffer* (__cdecl* MakeScreenShotD3DXBuffer)();
	void* (__cdecl* GetMainWindow)();
	void(__cdecl* SetPacketDelayTimeMS)(unsigned int);
	void(__cdecl* SetProcessGameTimeMS)(bool, unsigned int);
	bool(__cdecl* ProcessWindowMessages)();
	bool(__cdecl* IsEndMainLoop)();
	bool(__cdecl* IsInConnectTrouble)();
	float(__cdecl* GetPing)();
	void(__cdecl* DetachStandingObj)(LTObject*);
}; ILTClientDLL* oClientDLL;

class ILTCommon;

struct /*VFT*/ ILTCommon_vtbl
{
	const char* (__thiscall* _InterfaceImplementation)(IBase* pthis);
	unsigned int(__thiscall* GetObjectType)(ILTCommon* pthis, LTObject*, unsigned int*);
	unsigned int(__thiscall* CompressVector)(ILTCommon* pthis, const TVector3<float>*, CompVector*);
	unsigned int(__thiscall* UncompressVector)(ILTCommon* pthis, const CompVector*, TVector3<float>*);
	unsigned int(__thiscall* CompressRotation)(ILTCommon* pthis, const LTRotation*, CompRot*);
	unsigned int(__thiscall* Parse)(ILTCommon* pthis, ConParse*);
	unsigned int(__thiscall* GetModelAnimUserDims)(ILTCommon* pthis, LTObject*, TVector3<float>*, unsigned int);
	unsigned int(__thiscall* GetRotationVectors)(ILTCommon* pthis, LTRotation*, TVector3<float>*, TVector3<float>*, TVector3<float>*);
	unsigned int(__thiscall* SetupEuler)(ILTCommon* pthis, LTRotation*, float, float, float);
	unsigned int(__thiscall* CreateMessage)(ILTCommon* pthis, ILTMessage_Write**);
	unsigned int(__thiscall* GetPointStatus)(ILTCommon* pthis, const TVector3<float>*);
	unsigned int(__thiscall* GetPointShade)(ILTCommon* pthis, const TVector3<float>*, TVector3<float>*);
	unsigned int(__thiscall* GetPolyTextureFlags)(ILTCommon* pthis, HPOLY, unsigned int*);
	unsigned int(__thiscall* GetPolyPlane)(ILTCommon* pthis, HPOLY, LTPlane*);
	unsigned int(__thiscall* UncompressRotation)(ILTCommon* pthis, const CompRot*, LTRotation*);
	unsigned int(__thiscall* SetObjectResource)(ILTCommon* pthis, LTObject*, EObjectResource, unsigned int, const char*);
	unsigned int(__thiscall* SetObjectFilenames)(ILTCommon* pthis, LTObject*, ObjectCreateStruct*);
	unsigned int(__thiscall* GetObjectFlags)(ILTCommon* pthis, LTObject* const, const ObjFlagType, unsigned int*);
	unsigned int(__thiscall* SetObjectFlags)(ILTCommon* pthis, LTObject*, const ObjFlagType, unsigned int, unsigned int);
	unsigned int(__thiscall* SetObjectFlagsWithoutChangeFlags)(ILTCommon* pthis, LTObject*, const ObjFlagType, unsigned int, unsigned int);
	unsigned int(__thiscall* GetAttachmentObjects)(ILTCommon* pthis, HATTACHMENT_t*, LTObject**, LTObject**);
	unsigned int(__thiscall* GetAttachments)(ILTCommon* pthis, LTObject*, LTObject**, unsigned int, unsigned int*, unsigned int*);
	unsigned int(__thiscall* GetAttachedModelNodeTransform)(ILTCommon* pthis, HATTACHMENT_t*, unsigned int, Transform*);
	unsigned int(__thiscall* GetAttachmentTransform)(ILTCommon* pthis, HATTACHMENT_t*, Transform*, bool);
	unsigned int(__thiscall* GetAttachedModelSocketTransform)(ILTCommon* pthis, HATTACHMENT_t*, unsigned int, Transform*);
	unsigned int(__thiscall* NumAttachments)(ILTCommon* pthis, LTObject*, unsigned int*);
	unsigned int(__thiscall* EncodeCompressWorldPosition)(ILTCommon* pthis, CompWorldPos*, const TVector3<float>*);
	unsigned int(__thiscall* DecodeCompressWorldPosition)(ILTCommon* pthis, TVector3<float>*, const CompWorldPos*);
};
